from enum import Enum


class DisclosureStatus(str, Enum):

    DISCLOSED = "DISCLOSED"
    PARTIALLY_DISCLOSED = "PARTIALLY_DISCLOSED"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_FOUND = "NOT_FOUND"
    CONFLICTING = "CONFLICTING"


class EvidenceStrength(str, Enum):

    DIRECT = "DIRECT"
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    INFERRED = "INFERRED"


class Importance(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Confidence(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ExtractionStatus(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NO_READABLE_CONTENT = "NO_READABLE_CONTENT"


class DocumentType(str, Enum):
    PRIVACY_POLICY = "PRIVACY_POLICY"
    TERMS_OF_SERVICE = "TERMS_OF_SERVICE"
    TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS"
    SUBSCRIPTION_TERMS = "SUBSCRIPTION_TERMS"
    COOKIE_POLICY = "COOKIE_POLICY"
    EULA = "EULA"
    SERVICE_AGREEMENT = "SERVICE_AGREEMENT"
    REFUND_POLICY = "REFUND_POLICY"
    DATA_PROCESSING_AGREEMENT = "DATA_PROCESSING_AGREEMENT"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class FactCategory(str, Enum):
    DATA_COLLECTION = "DATA_COLLECTION"
    DATA_SHARING = "DATA_SHARING"
    DATA_USAGE = "DATA_USAGE"
    TRACKING = "TRACKING"
    ADVERTISING = "ADVERTISING"
    AI_USAGE = "AI_USAGE"
    RETENTION = "RETENTION"
    DELETION = "DELETION"
    SUBSCRIPTION = "SUBSCRIPTION"
    AUTO_RENEWAL = "AUTO_RENEWAL"
    TRIAL = "TRIAL"
    FEE = "FEE"
    REFUND = "REFUND"
    CANCELLATION = "CANCELLATION"
    ARBITRATION = "ARBITRATION"
    LIABILITY = "LIABILITY"
    TERMINATION = "TERMINATION"
    CONTENT_LICENSE = "CONTENT_LICENSE"
    GOVERNING_LAW = "GOVERNING_LAW"


class AssessmentLevel(str, Enum):
    MOSTLY_SAFE = "MOSTLY_SAFE"
    NOTHING_SIGNIFICANT_IDENTIFIED = "NOTHING_SIGNIFICANT_IDENTIFIED"
    REVIEW_RECOMMENDED = "REVIEW_RECOMMENDED"


class FinancialClarity(str, Enum):
    EXPLICIT = "EXPLICIT"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_CLEARLY_STATED = "NOT_CLEARLY_STATED"
    CONFLICTING = "CONFLICTING"



EvidenceType = EvidenceStrength
ConfidenceLevel = Confidence


class AnalysisStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
